stages:
  - build

before_script:
  - 'cat /etc/lsb-release && uname -a && pwd && ls -ashl'
  - 'node --version && npm --version && yarn --version'

build:
  stage: build
  script:
    - yarn
    - yarn build
    - tar -czvf build.tar.gz ./build
  artifacts:
    paths:
      - build.tar.gz
