stages:
  - build
  - deploy

before_script:
  - 'cat /etc/lsb-release && uname -a && pwd && ls -ashl'
  - 'node --version && npm --version && yarn --version'

build:
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  needs:
   - build
  environment: production
  before_script:
    - chmod 600 $DEPLOY_PRIVATEKEY
  script:
    - rsync -rvz -e "ssh -i $DEPLOY_PRIVATEKEY -o StrictHostKeyChecking=no" --delete build/ updater@jsgames:/opt/HomePage/
  only:
    - master
